apiVersion: v1
kind: Service
metadata:
  name: azure-mock
spec:
  selector:
    name: azure-mock
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Pod
metadata:
  name: azure-mock-pod
  labels:
    name: azure-mock
    component: mock
spec:
  hostname: devstoreaccount1
  subdomain: azure-mock
  containers:
  - image: mcr.microsoft.com/azure-storage/azurite:3.31.0
    command: ["azurite", "-l", "/data", "--blobHost", "0.0.0.0","--blobPort", "80"]
    name: azurite
    ports:
      - name: http
        containerPort: 80
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: azure-mock
spec:
  rules:
  - host: '*.azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: http
        path: /
        pathType: Prefix
  - host: 'azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: http
        path: /
        pathType: Prefix
  - host: '*.blob.azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: http
        path: /
        pathType: Prefix
  - host: 'blob.azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: http
        path: /
        pathType: Prefix
