name: "Install doc dependencies"
description: "Prepare required packages before building the documentation"

runs:
  using: composite
  steps:
    - name: Install required dependencies
      shell: bash
      run: |
        set -e

        install_packages() {
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            xindy \
            enchant \
            git \
            graphviz \
            curl \
            latexmk \
            make \
            ghostscript \
            inkscape \
            plantuml \
            python3 \
            python3-buildbot-worker \
            texlive-font-utils \
            python3-pip \
            texlive-fonts-extra \
            texlive-fonts-recommended \
            texlive-latex-extra \
            texlive-luatex \
            texlive-xetex \
            texlive-latex-recommended \
            tox \
            emacs \
            less
        }

        if ! install_packages; then
          echo "Switching to archive.ubuntu.com"
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update
          install_packages
        fi
    - name: Override plantuml
      shell: bash
      run: |
        sudo curl -f -Lo /usr/share/plantuml/plantuml.jar \
        https://sourceforge.net/projects/plantuml/files/plantuml.1.2019.9.jar
